#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := espnow_example
EXTRA_COMPONENT_DIRS := /Users/lee/Desktop/try/esp/esp-idf-lib/components

include $(IDF_PATH)/make/project.mk
